export const RESERVATION_HAS_ERRORED = "RESERVATION_HAS_ERRORED"
export const RESERVATION_IS_LOADING = "RESERVATION_IS_LOADING"
export const RESERVATIONS_FETCH_DATA_SUCCESS = "RESERVATIONS_FETCH_DATA_SUCCESS"
export const NEW_RESERVATION = "NEW_RESERVATION"
export const CANCEL_RESERVATION = "CANCEL_RESERVATION"
export const SEAT_RESERVATION = "SEAT_RESERVATION"

export const WAITLIST_HAS_ERRORED = "WAITLIST_HAS_ERRORED"
export const WAITLIST_IS_LOADING = "WAITLIST_IS_LOADING"
export const WAITLIST_FETCH_DATA_SUCCESS = "WAITLIST_FETCH_DATA_SUCCESS"
export const CANCEL_WAITLIST = "CANCEL_WAITLIST"
export const NEW_WAITLIST = "NEW_WAITLIST"
export const SEAT_WAITLIST = "SEAT_WAITLIST"

export const STATIC_TABLE_FETCH_SUCCESS ="STATIC_TABLE_FETCH_SUCCESS"
export const STATIC_SEAT_TABLE = "STATIC_SEAT_TABLE"
export const STATIC_CLEAR_TABLE = "STATIC_CLEAR_TABLE"
export const CREATE_TABLE = "CREATE_TABLE"
export const TABLE_FETCH_SUCCESS = "TABLE_FETCH_SUCCESS"
export const CLEAR_TABLE = "CLEAR_TABLE"
export const SELECT_TABLE = "SELECT_TABLE"

export const NEW_CUSTOMER = "NEW_CUSTOMER"
export const CUSTOMER_FETCH_DATA_SUCCESS = "CUSTOMER_FETCH_DATA_SUCCESS"
export const REMOVE_CUSTOMER = "REMOVE_CUSTOMER"

export const RECIPE_FETCH_DATA_SUCCESS = "RECIPE_FETCH_DATA_SUCCESS"

export const ORDER_FETCH_DATA_SUCCESS = "ORDER_FETCH_DATA_SUCCESS"
export const NEW_ORDER ="NEW_ORDER"

export const CURRENT_TAB = "CURRENT_TAB"
