export const RESERVATION_HAS_ERRORED = "RESERVATION_HAS_ERRORED"
export const RESERVATION_IS_LOADING = "RESERVATION_IS_LOADING"
export const RESERVATIONS_FETCH_DATA_SUCCESS = "RESERVATIONS_FETCH_DATA_SUCCESS"
export const NEW_RESERVATION = "NEW_RESERVATION"
export const CANCEL_RESERVATION = "CANCEL_RESERVATION"

export const WAITLIST_HAS_ERRORED = "WAITLIST_HAS_ERRORED"
export const WAITLIST_IS_LOADING = "WAITLIST_IS_LOADING"
export const WAITLIST_FETCH_DATA_SUCCESS = "WAITLIST_FETCH_DATA_SUCCESS"

export const STATIC_TABLE_FETCH_SUCCESS ="STATIC_TABLE_FETCH_SUCCESS"
export const SEAT_TABLE = "SEAT_TABLE"
